apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: data-visual
  name: data-visual
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: data-visual
    spec:
      containers:
      - name: data-visual
        image: 10.0.3.31:5000/gridvo/data-visual:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_SERVICE_HOST
          value: "mongodb"
        - name: MONGODB_SERVICE_PORT
          value: "27017"
        - name: DATA_COLLECT_SERVICE_HOST
          value: "data-collect"
        - name: DATA_COLLECT_SERVICE_PORT
          value: "80"
        - name: ZIPKIN_SERVICE_HOST
          value: "zipkin"
        - name: ZIPKIN_HTTP_TRANSPORT_PORT
          value: "9411"
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
             
