apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-visual
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: data-visual
    spec:
      containers:
      - name: data-visual
        image: 10.0.2.62:5000/gridvo/data-visual:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
             
